# Nombre de la aplicación
spring.application.name=operacion-ultima-milla

# Mostrar mensajes de error completos
server.error.include-message=always

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Base de datos H2 en archivo
spring.datasource.url=jdbc:h2:file:./data/gamevault
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect